export const SITE = {
  name: 'ONE 2 BUY Kiel',
  tagline: 'Kiels größter An- & Verkauf seit 1999',
  url: 'https://one2buy-kiel.de',
  shop: {
    address: 'Sophienblatt 19',
    zip: '24103',
    city: 'Kiel',
    country: 'Deutschland', 
    phone: '0431 6004839',
    phoneHref: 'tel:+4943160048039',
    email: 'otbkiel@web.de',
    emailHref: 'mailto:otbkiel@web.de',
    mapsEmbed: 'https://maps.google.com/maps?q=Sophienblatt+19,+24103+Kiel&output=embed&hl=de',
    mapsUrl: 'https://maps.google.com/?q=Sophienblatt+19,+24103+Kiel',
  },
  hours: [
    { days: 'Montag – Freitag', time: '9:00 – 19:00 Uhr', closed: false },
    { days: 'Samstag', time: '10:00 – 18:00 Uhr', closed: false },
    { days: 'Sonntag', time: 'Geschlossen', closed: true },
  ],
  ebay: {
    seller: '12ankaufonline',
    storeUrl: 'https://www.ebay.de/str/12ankaufonline',
    rssUrl: 'https://www.ebay.de/sch/i.html?_nkw=&_sasl=12ankaufonline&_sop=10&_rss=1',
  },
  impressum: {
    name: 'Juliette Petersen',
    address: 'Ascheberger Str. 4',
    zip: '24143',
    city: 'Kiel',
    country: 'Deutschland',
    phone: '+49 431 6004839',
    phoneHref: 'tel:+4943160048039',
    email: 'ebayotb@email.de',
    emailHref: 'mailto:ebayotb@email.de',
    ustId: 'DE 363829899',
  },
  nav: [
    { label: 'Startseite', href: '/' },
    { label: 'Ankauf', href: '/ankauf' },
    { label: 'Verkauf', href: '/verkauf' },
    { label: 'Goldankauf', href: '/goldankauf' },
    { label: 'Standort', href: '/standorte' },
    { label: 'Über uns', href: '/ueber-uns' },
    { label: 'Kontakt', href: '/kontakt' },
    { label: 'FAQ', href: '/faq' },
  ],
};
